### ISSUE TITLE
mod服无法使用

### ISSUE THREAD

**Issue by gundami** [bangbang93/minecraft-proxy#12]
纯净端能加载出服务器，mod端加载不出
版本1.12.2，forge2838

**Comment by bangbang93** [comment]
其他还带了什么mod吗，只有forge的话我试了试没问题

**Comment by gundami** [comment]
我服务器用的是forge2838，客户端是2847，什么mod都没加，多人游戏刷不出来，点进去报错

![image](https://user-images.githubusercontent.com/41334632/88263770-20f5e700-ccfd-11ea-95f5-bd6c2392ff47.png)
