### ISSUE TITLE
Proxy Hypixel时出现问题

### ISSUE THREAD

**Issue by MikeWu597** [bangbang93/minecraft-proxy#14]
在Hypixel中加入小游戏，
客户端提示：
`连接中断`
后端提示：
`{"name":"server","port":25565,"host":"0.0.0.0","hostname"="xxxx","pid":3662,"level":50,"err":{"errno":"EPIPE","code":"EPIPE","syscall":"write"},"msg":"write EPIPE","time":"xxxx","v":0}`
望解决

**Comment by bangbang93** [comment]
EPIPE代表是服务端或客户端主动断开连接，服务端有错误吗？

**Comment by MikeWu597** [comment]
也许这和Hypixel的架构有关……但是用iptables转发流量时并没有此bug

**Comment by MikeWu597** [comment]
其实我使用您的软件主要是想利用那个接管ping的功能，要是能把这个功能单独划出来做一个repo就好了

**Comment by bangbang93** [comment]
其实接管ping就是最深的功能了，再往后的数据包我也是不解析直接转发的
client <--> proxy <--> server，proxy两边的连接任意断一个，都有可能触发EPIPE错误，估计得要再观察一下

**Comment by MikeWu597** [comment]
懂了，谢谢

**Comment by MikeWu597** [comment]
那么是否有办法忽略任何一方的信号中断，强制继续进行流量转发呢？我想这个错误触发的原因是Hypixel的二级转发架构问题

**Comment by bangbang93** [comment]
tcp都断了……我往哪发啊

**Comment by MikeWu597** [comment]
他可能是有两次tcp，中间可能断掉一会……
总之明白了，谢谢
