### ISSUE TITLE
服务器图标那里我应该填什么

### ISSUE THREAD

**Issue by dnxzcraft** [bangbang93/minecraft-proxy#15]
就是server配置文件里面的favicon后面应该填什么

**Comment by bangbang93** [comment]
文件的base64 dataurl
就是`data:image/png;base64,`开头的一串base64字符串
可以用这个工具<http://tu.chacuo.net/imagetodataurl>

**Comment by dnxzcraft** [comment]
那请问如果我要重新载入这个会话，应该输入什么，谢谢

**Comment by bangbang93** [comment]
找见主进程的pid，然后
`kill -SIGUSR1 pid`

**Comment by dnxzcraft** [comment]
![380B35DA-0990-48BF-B323-97AB5613F5EB](https://user-images.githubusercontent.com/78397338/106562049-b273ca80-6564-11eb-96dc-0608df512c81.png)
我这个好像什么也没显示，服务器也没更新，qwq

**Comment by bangbang93** [comment]
程序没有命令，不是在程序里输入

**Comment by dnxzcraft** [comment]
请问支持白名单系统吗

**Comment by bangbang93** [comment]
配置文件有blockList段

**Comment by dnxzcraft** [comment]
那个是黑名单。。没有白名单嘛qwq

**Comment by bangbang93** [comment]
没有……

**Comment by dnxzcraft** [comment]
哦好的
