### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by him41111** [bangbang93/minecraft-proxy#17]
1.支持泛版本转发
2.支持使用源服务器ping信息
3.支持多域名

**Comment by bangbang93** [comment]
1. 版本只是客户端显示，并不影响实际逻辑，也不影响连接
2. handlePing: false，让mcproxy不处理ping，就可以源服务器ping信息了
3. 是指一个主机使用多个域名吗，这个倒是可以考虑一下

**Comment by him41111** [comment]
还有一个问题，不支持高版本，比如1.16.5

**Comment by bangbang93** [comment]
这我到还没试过，不过协议没改过理论上应该是通用的啊，有什么报错吗

**Comment by bangbang93** [comment]
> 还有一个问题，不支持高版本，比如1.16.5

Fixed in 8ffa0850e910d6775032097b63756c06b7e841b1

**Comment by him41111** [comment]
看来还需要自己编译，求懒人包！
