### ISSUE TITLE
建议更新支持到1.17版本

### ISSUE THREAD

**Issue by KnightBlood** [bangbang93/minecraft-proxy#23]
建议更新支持到1.17版本

**Comment by bangbang93** [comment]
理论上是直接支持的，你有遇到什么问题吗？

**Comment by KnightBlood** [comment]
提示不支持1.17版本
然后我试图升级各种依赖然后就编译不通过了

**Comment by KnightBlood** [comment]
> 理论上是直接支持的，你有遇到什么问题吗？

提示不支持1.17版本
然后我试图升级各种依赖然后就编译不通过了

**Comment by KnightBlood** [comment]
> 理论上是直接支持的，你有遇到什么问题吗？

话说这玩意像nginx一样 那多个MC服务器 怎么处理各个服务器之间的数据同步问题呢
毕竟MC不像网站一样往同一个数据库里写数据 节点不同获取的数据相同

**Comment by bangbang93** [comment]
> > 理论上是直接支持的，你有遇到什么问题吗？
> 
> 话说这玩意像nginx一样 那多个MC服务器 怎么处理各个服务器之间的数据同步问题呢
> 毕竟MC不像网站一样往同一个数据库里写数据 节点不同获取的数据相同

这个我管不了，有类似需求的可能更适合使用BungeeCord
