### ISSUE TITLE
defaultServer 不能删除，一删就报错

### ISSUE THREAD

**Issue by KnightBlood** [bangbang93/minecraft-proxy#24]
[
  ValidationError {
    target: Config {
      allowListOnly: false,
      proxy: [ConfigProxy],
      servers: [Array],
      blockList: [BlockList]
    },
    value: undefined,
    property: 'defaultServer',
    children: [],
    constraints: { isString: 'defaultServer must be a string' }
  }
]

**Comment by KnightBlood** [comment]
readme需要修改

**Comment by KnightBlood** [comment]
设为false的时候当作servername处理了

**Comment by bangbang93** [comment]
修了，允许删掉了
