### ISSUE TITLE
BLOCKSMC 连接超时？

### ISSUE THREAD

**Issue by lem0nb** [bangbang93/minecraft-proxy#28]
如题，hypixel也是这样
是美国vps网络问题吗？
但是ip可以ping通
s from 104.26.7.75: icmp_seq=2 ttl=55 time=1.41 ms
64 bytes from 104.26.7.75: icmp_seq=3 ttl=55 time=1.40 ms
64 bytes from 104.26.7.75: icmp_seq=4 ttl=55 time=1.46 ms

**Comment by lem0nb** [comment]
`{"name":"client","hostname":"rainyun","pid":4966,"remoteAddress":"*","remotePort":64194,"username":"LeeLiLee","level":50,"err":{"errno":-110,"code":"ETIMEDOUT","syscall":"connect","address":"104.26.7.75","port":25565},"msg":"connect ETIMEDOUT 104.26.7.75:25565","time":"2021-09-18T22:25:29.181Z","v":0}`

**Comment by bangbang93** [comment]
104.26.7.75是cf的ip，你这个服务器实际上使用的是SRV记录

> SRV _minecraft._tcp.blocksmc.com. 0s   10 10 "_dc-srv.35583ea59f7e._minecraft._tcp.blocksmc.com.":25565

所以你应当把后端地址指向srv记录

**Comment by lem0nb** [comment]
> 
> 
> 104.26.7.75是cf的ip，你这个服务器实际上使用的是SRV记录
> 
> > SRV _minecraft._tcp.blocksmc.com. 0s   10 10 "_dc-srv.35583ea59f7e._minecraft._tcp.blocksmc.com.":25565
> 
> 所以你应当把后端地址指向srv记录

感谢
