### ISSUE TITLE
Parsing packets

### ISSUE THREAD

**Issue by dig** [bangbang93/minecraft-proxy#3]
How can we listen to packets that are being sent to the server & to the client and parse them? (I'm guessing server.on("data") but then how would we parse it?

Thanks!

**Comment by bangbang93** [comment]
```javascript
var protocol = require('./protocol');
protocol.parsePacket(buffer, state, true, {
                set_protocol: 1,
                login_start: 1,
                ping: 1
            });
```

**Comment by DigitalSniperz** [comment]
That parses the packets but how do we listen to the packets being sent from the client & server. Example please? :)

Thanks!
