### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by Ligture** [bangbang93/minecraft-proxy#37]
麻烦看一下这是什么问题
]# bin/mcproxy
[
  ValidationError {
    target: Config {
      allowListOnly: false,
      profileEndpoint: 'https://api.mojang.com/profiles/minecraft',
      plugins: null,
      proxy: [ConfigProxy],
      defaultServer: 'hypixel',
      blockList: [BlockList],
      servers: [Array]
    },
    value: BlockList { ips: [Array], usernames: [Array], uuids: [Array] },
    property: 'blockList',
    children: [ [ValidationError] ]
  }
]

**Comment by bangbang93** [comment]
配置文件校验错误，你把配置文件发上来坎壈

**Comment by Ligture** [comment]
proxy:
  port: 25565
  host: 0.0.0.0
  workers: 0
defaultServer: hypixel
blockList:
  ips: !!import/single block-ip.yml
  usernames: !!import/single gg.yml
  uuids:
    - 12b8b9e0eba0ca37e935f037ff1ae90d
servers:
  !!import/sequence
  - servers/
profileEndpoint: https://api.mojang.com/profiles/minecraft
plugins:
#  - test



serverName: [hypixel]
proxyHost: mc.hypixel.net
proxyPort: 25565
version: 1.8.9
handlePing: true
onlineMode: true
ping:
  maxPlayer: 114514
  description: §6§lHypixel加速ip
  favicon: data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAAAAACPAi4CAAAA/WlDQ1BpY2MAACjPY2BgkmAAAhYDBobcvJKiIHcnhYjIKAUGJJCYXFzAgBswMjB8uwYiGRgu6zKQDjhTUouTgfQHIC4pAloONDIFyBZJh7ArQOwkCLsHxC4KCXIGshcA2RrpSOwkJHZ5SUEJkH0CpD65oAjEvgNk2+TmlCYj3M3Ak5oXGgykI4BYhqGYIYjBncGJDD/gBYjwzF/EwGDxlYGBeQJCLGkmA8P2VgYGiVsIMRWgH/hbGBi2nS9ILEoEC7EAMVNaGgPDp+UMDLyRDAzCFxgYuKIx7UDEBQ6/KoD96s6QD4TpDDkMqUART4Y8hmQGPSDLiMGAwZDBDACSpUCzt7J9uQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAAmJLR0QA/4ePzL8AAAAHdElNRQfmAgQOCwrw1IvXAAABPXpUWHRSYXcgcHJvZmlsZSB0eXBlIGljYwAAOMutVFuShCAM/OcUewTIE4+jIFV7/wtsMLDj7OjHTG1XIRpj59HB8F1K+OpglBA7IOU4QXhsUmVXUmAgJYDImRdeId4hSBJU1PghUr80ixrmQ0dFqJ8yhjf9FyFhRfH6YxtmpWBdOKr3RIVGxiR6tmv+tT/55zLtnYisoR4hrSMCZCO6tt/4B1XTxlLzF+UR2QRQmPY6ImOxvhblWdqj6bNHRVh2Zh4OPAmNQM3GprvFi3Sr/7vN/jfVXjAH9YlImo8u5sbekuVyogWWpe+bZnbx6hquHIGGGi0fzd6kNI2SFCSd3Gi6i+HIqMHqZ6TyESnhGPCVt7tSzrg8Infyjv2PupMwleCyShur35vkwu5ElqHstuxD2N2Gduk8aOT2+/gBYjfc+z9pX8MAAAABb3JOVAHPoneaAAAAJXRFWHRkYXRlOmNyZWF0ZQAyMDIyLTAyLTA0VDE0OjEwOjUyKzAwOjAwwQ6uaQAAACV0RVh0ZGF0ZTptb2RpZnkAMjAyMi0wMi0wNFQxNDoxMDo1MSswMDowMIG7DEgAAAAedEVYdGljYzpjb3B5cmlnaHQAR29vZ2xlIEluYy4gMjAxNqwLMzgAAAAUdEVYdGljYzpkZXNjcmlwdGlvbgBzUkdCupBzBwAACwBJREFUWMN1Vwd0FWUWnjfttRQSkFAExUVdsaIc2q5SREWRFRFBDWChLAgE3UVAERuGFVRglyZNBEIkKKIgJUDohpCCKaSXl0LK61P+MjPPPWfvvAAhedl5782cSeb/7ne//9479zL0loPA11Byu7MWC2NpO1jWPDEcx1jYm3+Euz7nKTYY7fpBW38UkRk2rnVNewCBYRm+DRfuuuzDhnoT4AYOrepps4Ct64+yNwAsooPhb4Flwcp8SaXtGJgXeafNBuitAEwbA+HpHgLHtvkA65knSQQAJb4kFghwrQ/eooRzXZrDwrfdM6DCPTJBHVygpOkphudNCh00iE31zbTxLHNDHRBEiPUg2hEA5/a0wPpW2yzHmc+Hf/3y0dUneP6mvBzDiNG5pCMAQUeF69YZIMnz3A2AR5oQOuSwtbnAWxjxM4zbAYAOaJOpTpgiw4rxD/MW3lzPcGObMUZHExx2WAr0Wfg/xz4s3bqNuk41nSbZQcKwBY5hxyVa4UlgwQl/JzIN+v/dned4gAZ6pqKxmUY7AAKhuACcC/NjBE78djEAWEAIUfgkLcdPSHBTDBPNmwrChxXtn/tvAoTNE4IXmiZgu23gelzFRzaWB584wbm80qsqdSWVS21WkJiDOBAYYcJsbxsDQnU4qc/cI5oURfiww9RkpxBOAX6A5Mna/tqzTz8xzCrCLS+GAdZ+Vd7GIBxKKDBrQbTAmwrBPs8Jbh5oZ0xBrbOUhuEJVrtjwQuMk7Py0aPiwQi/trDuFgDIA031/vShGQQgFM+KP+GDa5yMiRe9R8m+sKnP7DdmJEOgPzTp1ZNzo3lG2CB5mDYPgIJBA75/CIBgusknpH0/a6CDcwLnrpclFWUfCaiZUxw28b2kPQeSY6MYbhMi7USEE5IWc62ByFrtvWLE2/7aZ4JVEEaVEypV/rjjZNkAXmQnp2yvPfainbds0VAHAA0r/7SZsQdBb72vq+2ugRkzltn5uA9l/7VrQbfqcfXryscPqdr187Ekuy16FyEd6wFBK6wgAMNCOCwbsquptOzMBqdtwN/eHPnY8Of3Fnw9tqfNPiDF7248+67tvsFbFaNDKOtU2WxnofqABnGZm13Zxz15r9iGlhZUl5QUVTQjafOH3aIfOKR4ruYtcYxcfFpTIgDo1jjYZ4FjhAHlJZU+/+nk2b13ugNEU1Bz7o8pn27pJg45LNdXZC61v/hDY9CIcIFsi38+qrvACtaFasCbvXx/0ftfICwjjfjh0iRlOIUR21yFZScmC/PrPQhHiIg29N755/FdbBYhccORHXu+K6rc7mp25ZeWHtu6+8jZtYXvRNm/Obz0wM+rP4g97pU0GrGN6sevF6zc9heHXXzoWP7Bz7Kx3Lg7Jf3Y3iVzN07/teDleT2FmKtlo1atfPN83yaVEi2iIqFlucG9Jd/EiXyPLUkr/H53zdFXp7SovvXHrmaWFs1/tIvQtbbiXxkDS/2LvDrWIksa2tkk/1aeMZjjxUkpVedX5/hyxk/YV1rwYVLyL0XFS4d0c3S/kvX1mLe96JoE0Ysjiqpcg1UlJ32s6LT2XbHqh2fzPEfHTBtZ3uJ6/e43fmlMffJPloTvD/d5phojzSA0FBlIiqrqNHhljsNuE0Y3/zr6rR8XTUwbuSinuKLgi/V1V2ZuSpj4YL+YGT6MVUKJrke8mTSMMZXV/fGOGHvfuYmDRh1Y+dz0p6aVEZnUzpud+vz0sSWJNstCFWshCiVMi3y1UeMPGpLRHXGMpfuoVevWl387dvTwUdsypu/J+PK76iX916KJsY7lYB0ZwCDi1aZRg1JMiTJ7zlDH+DcT1188t3jY/I0LHz+78qPkRfn5vmezrvbq9tF6haL/IlXXtQgA3RRCNejxU3udw3eMfm//B6PGbNm+ecHeosKcGnfQPTXvKbZn/WGKNaTrRqQLYSSozuRaju/+qMHT5lWcyLlEJaT6ZUKREjg49Ysotr+iEJMpDWmdAIQTguKW8uBXCc88t9XrkxUETmmwuv7KhbGrpna191GDGCsgoRIRSNddoFCZVDX3/ZJJ494/k5N9+Ux2bl5h+ulqqS71xdv/M87plgkxiKJjEuoUAMghRZUDqcH8ZZ8smHu8qPDIvqwmWVGr9j/UM0Xa33/7mbqqiqIGpHfCINznaBo2ILla3HJ1v7hHD1R4/FhtQYaaMSR6SgvNnZ18pqEp8/cdkIza/wMgcKKSQjwToxJePld84sjFIl/jjt6QCL5Q5e/+nCp3Ue1FYlC9cxGhW1M1SSWooWxRlLXXWxsvtMgFyU+IXMJuVca1NSToysj4OQcH/9A60UAPbyOVPUrgTLrrcBdWEBy9Hx3W18ly1mluOYhr6pFMKipqL+apOolkoOtQvmSvu/zCtndOBeWcOwWW5Z2Cgxds3B3noUAAA12ST/v0qkxNj2QA8W2o2JVX4HHXX64jasNwq2AxmwlGEBMOYCL50JVCghurDam+Ru9EREMniATSj2oBdKHCI1PPDEYQzH4EXqZrZU0NNpPcKzquV1GotIl0FomE/oFQy0+emjx/np9i+Wu7YL4ooWGa5NIwDdQqORc0JMOmnlIM3ImIsB5TvGd1vk9qagATl3oPihWhIbH2yA7K1Ag2ooLLBCKIZqcHg9joJA6wHgri1IsqIlIR1kjtg78u7+uE1voShQwgkl+rq0chyK7zL5xFpJNIxAZR5fJzGGqOkgttUfF9DRVlS56++2NFxpCQUgDVNCgEyQ1Fg+5dkql2EgdYw/7THgRhRqQSCeV2KwxUB6qKveAOVYMtflxcZijEXegZLzruXdMegIYTiapqdT00XJqqVEn48IgsyaVgAowo9UqNSDt3MYTQmhXyEt7KiZHbiDRVRoHKzEpECCn1oV39a5DkRq0VxO9qIvhkoRLY07132mYBer3IQNINaBiRPCuxBjajppkemhVUNa+CTA5YLlewd4eXnkp0WmPH2zhOiKzKIJRMGxbH3JWdkZkvleLsTym8A4kBMR6iciPVvMWBzC+nsYIY7kKYDgpC6cJIzZ9gZXu0VL/yeF6JWvyBCvIBf0BXrnk0VNBcNmLfGN7S2vAy7SSELcBKyLXaLojW+Nr03vy84uZrKxU9nCI64HihDp5wT57cMtQOLXm45W5XR3SKVX9gpgO6NMaWPpsXx22pCLxLDRzCBNonXfP7Gi8e/rzP73WPQUvOhLvuDgBIvjQiBppYaLVndGPtm+Z41XlQe80Sg5Dmq851p6T0mui/fBcPUxxMHSzTqpxmmCWMIqoUj7YCOUAXeItgS3s9U0nNgQxXAj5N9XldXt/2hC4pysFe16cqC2M6Hi5CIXgZqOrVl6IsXHjwNOnF7p88rrHlyxPnXcFDWe7CGqkpUPgYNyD32g99bwEAfgYQ0AmmwbP3R4V9gwJiThr2X+bettub5fWVNFUn3bsRyoH8np1PdPtSe9wEIObROrIqeZ/Gw5RkTiymE9DtWdPWCePcBVIArKCgWSibB7CO7z3qri7cjdkJ5AXtIVJDwZODrFFhYcMjjwhfx8S3bXH7q92qDCog2Er5/APc3S5JXWe9MYGaDCDOiIZb3o2xmFMhfAEFggwmF7ZXvMD3Pzpz6REIZ6zKRiCtO/NSE1JWijcBgBvkGZGzxomiKJgDU3hKCyvBW+6MswKNoYPnNKtE8dRkHlxjc6YoSnC5cBMAMgZCNVA3wmo3bXOmfUv4CjMj2/8RuyjGDJkytU4m+m+vvvZ4X/H2RhmpScL12dTyP+GFvwNfOveEAAAAWmVYSWZNTQAqAAAACAAFARIAAwAAAAEAAQAAARoABQAAAAEAAABKARsABQAAAAEAAABSASgAAwAAAAEAAgAAAhMAAwAAAAEAAQAAAAAAAAAAAEgAAAABAAAASAAAAAEfUvc0AAAAAElFTkSuQmCC

**Comment by Ligture** [comment]
之前用都是正常的 然后关掉一次之后就打不开了

**Comment by bangbang93** [comment]
```yaml
blockList:
  ips: !!import/single block-ip.yml
  usernames: !!import/single gg.yml
  uuids:
    - 12b8b9e0eba0ca37e935f037ff1ae90d
```
`block-ip.yml`和`gg.yml`呢

**Comment by Ligture** [comment]
block-ip.yml
- 114.114.114.114
- 10.0.0.0/32







gg.yml
- lpmon
- PerssonBrown
- Minecraft_ay3657
- Just_dust2005
- NineQ
- MiddleJam260220
- HackerLoser_
- LeadYttrium
- Mliky_Dad
- Ultro_loli_sec
- 2008Mojit

**Comment by bangbang93** [comment]
刚刚更新了一个版本，你更新一下看看报错具体是什么内容

**Comment by Ligture** [comment]
试不了了 我把我另外一个服务器上的配置复制过来了已经好了 两个的配置文件只有gg.yml内容不一样我估计是黑名单的问题
