### ISSUE TITLE
Show real latency when using handlePing mode

### ISSUE THREAD

**Issue by reekystive** [bangbang93/minecraft-proxy#41]
When handlePing is enabled, the latency shown in Minecraft is the latency to the proxy server, not the actual latency.

使用接管 ping 时，游戏中显示的延迟是到代理服务器的延迟，并不是真正的游戏延迟。

是否有办法做到显示真正的延迟（客户端 -> 代理服务器 + 代理服务器 -> 真实服务器）？

**Comment by bangbang93** [comment]
那就不要接管ping……
