### ISSUE TITLE
如何添加新的服务器

### ISSUE THREAD

**Issue by LFMJUN** [bangbang93/minecraft-proxy#44]
折腾了半天，/config/server里我也加了服务器，可是输出还是默认服务器，尝试把defaultServer注释掉，也没有办法，是还要改别的吗
{"name":"master","hostname":"VM19901","pid":25635,"level":30,"msg":"all workers started","time":"2022-02-19T14:20:53.230Z","v":0}
{"name":"server","port":25565,"host":"0.0.0.0","worker":1,"hostname":"VM19901","pid":25652,"level":30,"msg":"ready","time":"2022-02-19T14:20:54.193Z","v":0}

**Comment by bangbang93** [comment]
日志输出里不含有服务器信息的
