### ISSUE TITLE
无法正确代理1.18.1mod服务器

### ISSUE THREAD

**Issue by mocksonline** [bangbang93/minecraft-proxy#50]
无法正确代理1.18.1mod服务器，可以得到服务器端的信息但是最后客户端会提示"中转服务器ip" not found
服务端后台无输出
客户端服务端是forge 1.18.1 最新版（搞忘了懒得翻了）
如果需要其他的东西可以提供（不知道写啥）
config.yml没动，然后只更改了./servers里面的配置：

serverName: 纯数字名字
proxyHost: mc服务端地址
proxyPort: 25565
version: 1.18.1
handlePing: false
onlineMode: false
useProxy: false

**Comment by mocksonline** [comment]
mcproxy后台会提示{"name":"client","hostname":"C20220509067672","pid":13001,"remoteAddress":"IP地址1","remotePort":43114,"username":"*","level":30,"msg":"force disconnecting [object Object], reason: IP地址2 not found","time":"2022-05-09T19:19:00.359Z","v":0}

**Comment by mocksonline** [comment]
更新#1 测试了纯净forge 1.18.1 39.1.2版本（服务端和客户端同版本）也出现了上述情况

**Comment by mocksonline** [comment]
测试了1.18.1和1.17.1原版，也是一样。可能是没有脸上，请作者帮忙看看有没有问题，谢谢

**Comment by bangbang93** [comment]
serverName需要设置为“中转服务器ip”
