### ISSUE TITLE
新功能提议：多端口转发

### ISSUE THREAD

**Issue by outtimes** [bangbang93/minecraft-proxy#6]
想请问是否后续考虑支持范围端口转发？比如A服务器配置了minecraft-proxy并持有公网IP，同时在B服务器上运行了多个Minecraft服务器，由于B服务器的链路质量不佳或仅有单线网络，但A服务器链路质量佳，能否通过配置，访问A服务器的10001-20001端口即自动转发到B服务器:10001-20001。

**Comment by bangbang93** [comment]
这和我的初衷不太一致，暂时不考虑
