### ISSUE TITLE
新功能建议：使用KCP协议作为中转代理

### ISSUE THREAD

**Issue by Matrixchung** [bangbang93/minecraft-proxy#8]
基本结构：服务端TCP-代理KCP-长距离网络-客户端软件KCP-客户端TCP
KCP协议地址：[https://github.com/skywind3000/kcp](url)
从协议上看能有效解决Minecraft自身的TCP协议所带来的丢包、断链、超时等问题，加入代理又不至于对Minecraft端进行魔改，能更好兼容各个版本。
能不能用KCP协议对所有出/入的Packets封包做转发，在客户端本地额外增加一个软件进行解码，从而使面向Minecraft的两端都使用TCP协议，不至于魔改mc。
编程萌新一枚，求大佬指点一二！

**Comment by bangbang93** [comment]
理论上是可行的，kcp的文档里也给出了实现方法

**Comment by Matrixchung** [comment]
> 理论上是可行的，kcp的文档里也给出了实现方法

目前我使用KCPTun已经基本实现代理= =昨天晚上发issue的时候还没找到这个工具，给玩家试用了一下确实有很大的提升
